// Generated by custom-push — edit as needed.
import { usePushNotification } from 'custom-push/runtime'
import ourPkg from '../../our_pkg.json'

export function usePush() {
  return usePushNotification({
    firebase: ourPkg.firebase,
    backend: {
      registerUrl:   ourPkg.backend.registerUrl,
      unregisterUrl: ourPkg.backend.unregisterUrl || undefined,
      getAuthToken:  () => localStorage.getItem('auth_token') ?? '',
    },
    options: {
      onMessage: (payload) => {
        // Foreground push received — plug in your toast library here
        console.log('[push] foreground:', payload.title, payload.body)
      },
      onReady: (token) => {
        console.log('[push] ready. token:', token)
      },
      onPermissionDenied: () => {
        console.warn('[push] permission denied')
      },
      onError: (err) => {
        console.error('[push] error:', err.message)
      },
    },
  })
}
