// Generated by custom-push — edit as needed.
import * as admin from 'firebase-admin'
import * as path from 'path'
import ourPkg from '../our_pkg.json'

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(
      path.resolve(ourPkg.backend.credentialsPath ?? './credentials.json')
    ),
  })
}

export async function sendPushNotification(params: {
  token: string
  title: string
  body: string
  data?: Record<string, string>
  route?: string
}): Promise<string> {
  const message: admin.messaging.Message = {
    token: params.token,
    notification: { title: params.title, body: params.body },
    data: { ...(params.data || {}), route: params.route || '/' },
    webpush: {
      notification: { title: params.title, body: params.body, icon: '/icon.png' },
    },
  }
  return admin.messaging().send(message)
}
