// Generated by custom-push — edit as needed.
const admin = require('firebase-admin')
const path = require('path')
const ourPkg = require('../our_pkg.json')

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(
      path.resolve(ourPkg.backend.credentialsPath ?? './credentials.json')
    ),
  })
}

async function sendPushNotification(params) {
  const message = {
    token: params.token,
    notification: { title: params.title, body: params.body },
    data: { ...(params.data || {}), route: params.route || '/' },
    webpush: {
      notification: { title: params.title, body: params.body, icon: '/icon.png' },
    },
  }
  return admin.messaging().send(message)
}

module.exports = { sendPushNotification }
