// Generated by custom-push — edit as needed.
const { Router } = require('express')

const router = Router()

// POST /push/register
router.post('/register', async (req, res) => {
  try {
    const { token } = req.body
    if (!token) return res.status(400).json({ error: 'token is required' })
    // TODO: get userId from your auth middleware (e.g. req.user.id)
    // await db.pushTokens.upsert({ userId, token })
    res.json({ success: true })
  } catch {
    res.status(500).json({ error: 'Failed to register token' })
  }
})

// POST /push/unregister
router.post('/unregister', async (req, res) => {
  try {
    const { token } = req.body
    if (!token) return res.status(400).json({ error: 'token is required' })
    // TODO: await db.pushTokens.delete({ token })
    res.json({ success: true })
  } catch {
    res.status(500).json({ error: 'Failed to unregister token' })
  }
})

module.exports = router
