import * as path from 'path'
import { CLIContext, ScaffoldedFile } from '../types'
import { logger } from '../utils/logger'
import { readFile, writeFile, ensureDir, fileExists } from '../utils/fileUtils'
import { renderTemplate } from '../core/templateEngine'
import { checkConflicts } from '../core/checkConflicts'
import {
  TEMPLATES_DIR,
  SW_TEMPLATE,
  FRONTEND_HELPER_TS,
  FRONTEND_HELPER_JS,
  SERVICE_WORKER_FILENAME,
  SERVICE_WORKER_FALLBACK_FILENAME,
  FRONTEND_MANAGER_TPL,
  FRONTEND_MANAGER_JSX,
  FRONTEND_CONFIG_TPL,
  FRONTEND_CONFIG_JS,
  FRONTEND_PUSH_PROVIDER_TSX,
  FRONTEND_PUSH_PROVIDER_JSX,
  FRONTEND_USAGE_TPL,
  FRONTEND_USAGE_REACT_JS_TPL,
  FRONTEND_USAGE_NEXTJS_TPL,
  FRONTEND_USAGE_NEXTJS_JS_TPL,
} from '../constants'

export async function scaffoldFrontend(context: CLIContext): Promise<ScaffoldedFile[]> {
  const { project, answers } = context
  const scaffolded: ScaffoldedFile[] = []

  // ── Determine service worker filename ─────────────────────────────────
  const defaultSwPath = path.join(project.publicDir, SERVICE_WORKER_FILENAME)
  let swFilename = SERVICE_WORKER_FILENAME

  if (await fileExists(defaultSwPath)) {
    // Check if it was generated by us (contains our comment header)
    const existingContent = await readFile(defaultSwPath)
    if (!existingContent.includes('Generated by QuickFCM')) {
      swFilename = SERVICE_WORKER_FALLBACK_FILENAME
      logger.warn(`⚠  ${SERVICE_WORKER_FILENAME} already exists and was not generated by QuickFCM.`)
      logger.info(`   Creating ${SERVICE_WORKER_FALLBACK_FILENAME} instead.`)
    }
  }

  context.serviceWorkerFilename = swFilename

  // ── 1. Service Worker ─────────────────────────────────────────────────
  const swTemplatePath = path.join(TEMPLATES_DIR, SW_TEMPLATE)
  const swTemplate = await readFile(swTemplatePath)

  const swContent = renderTemplate(swTemplate, {
    API_KEY: answers.firebase.apiKey || '',
    AUTH_DOMAIN: answers.firebase.authDomain || '',
    PROJECT_ID: answers.firebase.projectId || '',
    STORAGE_BUCKET: answers.firebase.storageBucket || '',
    MESSAGING_SENDER_ID: answers.firebase.messagingSenderId || '',
    APP_ID: answers.firebase.appId || '',
  })

  const swPath = path.join(project.publicDir, swFilename)

  // ── 2. Frontend Helper ────────────────────────────────────────────────
  const helperTemplate = project.language === 'typescript' ? FRONTEND_HELPER_TS : FRONTEND_HELPER_JS
  const ext = project.language === 'typescript' ? 'ts' : 'js'
  const helperTemplatePath = path.join(TEMPLATES_DIR, helperTemplate)
  const helperContent = await readFile(helperTemplatePath)

  // ── Ensure directories exist ──────────────────────────────────────────
  // hasSrc: true when srcDir !== rootDir (user chose yes to src/ in create-next-app)
  // Controls the relative depth from NotificationHandler/ to quickfcm.config.json:
  //   with src/:    src/NotificationHandler/pushHelper.ts  → ../../quickfcm.config.json
  //   without src/: NotificationHandler/pushHelper.ts      → ../quickfcm.config.json
  const hasSrc = project.srcDir !== project.rootDir
  const CONFIG_IMPORT_PATH = hasSrc
    ? '../../quickfcm.config.json'
    : '../quickfcm.config.json'

  const handlerDir = path.join(project.srcDir, 'NotificationHandler')
  await ensureDir(handlerDir)

  const helperPath = path.join(handlerDir, `pushHelper.${ext}`)

  // ── Render helper template with dynamic config import path ──────────────
  const renderedHelperContent = renderTemplate(helperContent, { CONFIG_IMPORT_PATH })

  // ── 3. Zero-Config Handler Files ──────────────────────────────────────
  const isTs = project.language === 'typescript'
  const jsxExt = project.jsxExtension  // 'tsx' | 'jsx' | 'js'

  // Manager template: tsx for TS, jsx/js template for JS (same JSX content, different output ext)
  // Config:  .ts for TS, .js for JS — logic files, never need JSX extension
  // Usage:   4-way pick — framework × language
  const managerTplName = isTs ? FRONTEND_MANAGER_TPL : FRONTEND_MANAGER_JSX
  const configTplName  = isTs ? FRONTEND_CONFIG_TPL  : FRONTEND_CONFIG_JS
  const usageTplName   = project.isNextJs
    ? (isTs ? FRONTEND_USAGE_NEXTJS_TPL   : FRONTEND_USAGE_NEXTJS_JS_TPL)
    : (isTs ? FRONTEND_USAGE_TPL          : FRONTEND_USAGE_REACT_JS_TPL)

  const managerTemplate = await readFile(path.join(TEMPLATES_DIR, managerTplName))
  const configTemplate  = await readFile(path.join(TEMPLATES_DIR, configTplName))
  const usageTemplate   = await readFile(path.join(TEMPLATES_DIR, usageTplName))

  // Output extensions
  // jsxExt drives component files (tsx | jsx | js)
  // configExt is always plain ts/js — never needs jsx suffix
  const configExt = isTs ? 'ts' : 'js'

  logger.info(`ℹ  Detected component extension: .${jsxExt}`)

  const managerPath = path.join(handlerDir, `PushNotificationManager.${jsxExt}`)
  const configPath  = path.join(handlerDir, `config.${configExt}`)
  const usagePath   = path.join(handlerDir, 'USAGE.md')

  // Template vars — SW_FILENAME needed by config template for serviceWorkerPath
  // CONFIG_IMPORT_PATH is the relative path from NotificationHandler/ to quickfcm.config.json
  const configVars: Record<string, string> = {
    SW_FILENAME: swFilename,
    CONFIG_IMPORT_PATH,
  }

  // Display-friendly paths for the USAGE.md doc (relative to project root)
  // HANDLER_DIR:   where NotificationHandler lives on disk (for the user to know)
  // COMPONENTS_DIR: where PushProvider lives (Next.js only)
  // JSX_EXT:        the component file extension detected for this project
  const HANDLER_DIR    = hasSrc ? 'src/NotificationHandler' : 'NotificationHandler'
  const COMPONENTS_DIR = hasSrc ? 'src/components'          : 'components'
  const JSX_EXT        = jsxExt

  const usageVars: Record<string, string> = {
    HANDLER_DIR,
    COMPONENTS_DIR,
    JSX_EXT,
  }

  // ── Run conflict checks ───────────────────────────────────────────────
  const filesToWrite = [
    {
      path: swPath,
      content: swContent,
      description: 'Firebase service worker — handles background push',
    },
    {
      path: helperPath,
      content: renderedHelperContent,
      description: 'Frontend helper — initializes and handles tokens',
    },
    {
      path: managerPath,
      content: renderTemplate(managerTemplate, usageVars),
      description: 'Zero-config Notification Manager component',
    },
    {
      path: configPath,
      content: renderTemplate(configTemplate, configVars),
      description: 'Firebase configuration file',
    },
    {
      path: usagePath,
      content: renderTemplate(usageTemplate, usageVars),
      description: 'Quick usage guide for your NotificationHandler',
    },
  ]

  // ── Next.js only: scaffold PushProvider into components/ ────────────────
  if (project.isNextJs) {
    // Prefer srcDir/components, fall back to rootDir/components; create if missing
    const componentsDirCandidates = [
      path.join(project.srcDir, 'components'),
      path.join(project.rootDir, 'components'),
    ]
    let componentsDir = componentsDirCandidates[0] // default: srcDir/components
    for (const candidate of componentsDirCandidates) {
      if (await fileExists(candidate)) {
        componentsDir = candidate
        break
      }
    }

    // ensureDir creates it if it doesn't exist
    await ensureDir(componentsDir)

    const providerTplName  = isTs ? FRONTEND_PUSH_PROVIDER_TSX : FRONTEND_PUSH_PROVIDER_JSX
    const providerTemplate = await readFile(path.join(TEMPLATES_DIR, providerTplName))
    filesToWrite.push({
      path: path.join(componentsDir, `PushProvider.${jsxExt}`),
      content: renderTemplate(providerTemplate, usageVars),
      description: 'Client-side PushProvider wrapper for Next.js layout',
    })
  }

  const resolved = await checkConflicts(filesToWrite, project)

  // ── Write resolved files ──────────────────────────────────────────────
  for (const file of resolved) {
    const relativePath = path.relative(project.rootDir, file.path)

    if (file.action === 'skip') {
      scaffolded.push({
        absolutePath: file.path,
        relativePath,
        status: 'skipped',
        description: file.description,
      })
    } else {
      await writeFile(file.path, file.content)
      scaffolded.push({
        absolutePath: file.path,
        relativePath,
        status: file.path === swPath && swFilename === SERVICE_WORKER_FALLBACK_FILENAME ? 'created' : 'created',
        description: file.description,
      })
    }
  }

  // ── Post-scaffold info ────────────────────────────────────────────────
  if (swFilename !== SERVICE_WORKER_FILENAME) {
    logger.blank()
    logger.warn(`⚠  Service worker created as: public/${swFilename}`)
    logger.info(`   Update your config to use serviceWorkerPath: '/${swFilename}'`)
  }

  return scaffolded
}
