import * as path from 'path'
import { CLIContext, ScaffoldedFile } from '../types'
import { logger } from '../utils/logger'
import { readFile, writeFile, ensureDir, fileExists } from '../utils/fileUtils'
import { renderTemplate } from '../core/templateEngine'
import { checkConflicts } from '../core/checkConflicts'
import {
  TEMPLATES_DIR,
  SW_TEMPLATE,
  FRONTEND_HELPER_TS,
  FRONTEND_HELPER_JS,
  SERVICE_WORKER_FILENAME,
  SERVICE_WORKER_FALLBACK_FILENAME,
  FRONTEND_MANAGER_TPL,
  FRONTEND_MANAGER_JSX,
  FRONTEND_CONFIG_TPL,
  FRONTEND_USAGE_TPL,
} from '../constants'

export async function scaffoldFrontend(context: CLIContext): Promise<ScaffoldedFile[]> {
  const { project, answers } = context
  const scaffolded: ScaffoldedFile[] = []

  // ── Determine service worker filename ─────────────────────────────────
  const defaultSwPath = path.join(project.publicDir, SERVICE_WORKER_FILENAME)
  let swFilename = SERVICE_WORKER_FILENAME

  if (await fileExists(defaultSwPath)) {
    // Check if it was generated by us (contains our comment header)
    const existingContent = await readFile(defaultSwPath)
    if (!existingContent.includes('Generated by QuickFCM')) {
      swFilename = SERVICE_WORKER_FALLBACK_FILENAME
      logger.warn(`⚠  ${SERVICE_WORKER_FILENAME} already exists and was not generated by QuickFCM.`)
      logger.info(`   Creating ${SERVICE_WORKER_FALLBACK_FILENAME} instead.`)
    }
  }

  context.serviceWorkerFilename = swFilename

  // ── 1. Service Worker ─────────────────────────────────────────────────
  const swTemplatePath = path.join(TEMPLATES_DIR, SW_TEMPLATE)
  const swTemplate = await readFile(swTemplatePath)

  const swContent = renderTemplate(swTemplate, {
    API_KEY: answers.firebase.apiKey || '',
    AUTH_DOMAIN: answers.firebase.authDomain || '',
    PROJECT_ID: answers.firebase.projectId || '',
    STORAGE_BUCKET: answers.firebase.storageBucket || '',
    MESSAGING_SENDER_ID: answers.firebase.messagingSenderId || '',
    APP_ID: answers.firebase.appId || '',
  })

  const swPath = path.join(project.publicDir, swFilename)

  // ── 2. Frontend Helper ────────────────────────────────────────────────
  const helperTemplate = project.language === 'typescript' ? FRONTEND_HELPER_TS : FRONTEND_HELPER_JS
  const ext = project.language === 'typescript' ? 'ts' : 'js'
  const helperTemplatePath = path.join(TEMPLATES_DIR, helperTemplate)
  const helperContent = await readFile(helperTemplatePath)

  // ── Ensure directories exist ──────────────────────────────────────────
  const handlerDir = path.join(project.srcDir, 'NotificationHandler')
  await ensureDir(handlerDir)

  const helperPath = path.join(handlerDir, `pushHelper.${ext}`)

  // ── 3. Zero-Config Handler Files ──────────────────────────────────────
  const isTs = project.language === 'typescript'
  const envPrefix = project.isNextJs ? 'NEXT_PUBLIC_' : ''

  // Manager: .tsx for TS, .jsx for JS
  const managerTplName = isTs ? FRONTEND_MANAGER_TPL : FRONTEND_MANAGER_JSX
  const managerTemplate = await readFile(path.join(TEMPLATES_DIR, managerTplName))
  const configTemplate  = await readFile(path.join(TEMPLATES_DIR, FRONTEND_CONFIG_TPL))
  const usageTemplate   = await readFile(path.join(TEMPLATES_DIR, FRONTEND_USAGE_TPL))

  // Output extensions
  const managerExt = isTs ? 'tsx' : 'jsx'
  const configExt  = isTs ? 'ts'  : 'js'

  const managerPath = path.join(handlerDir, `PushNotificationManager.${managerExt}`)
  const configPath  = path.join(handlerDir, `config.${configExt}`)
  const usagePath   = path.join(handlerDir, 'USAGE.md')

  // Template vars for pushConfig — aligns with Phase 2 FCM_ key names
  const configVars: Record<string, string> = {
    ENV_PREFIX: envPrefix,
  }

  // ── Run conflict checks ───────────────────────────────────────────────
  const filesToWrite = [
    {
      path: swPath,
      content: swContent,
      description: 'Firebase service worker — handles background push',
    },
    {
      path: helperPath,
      content: helperContent,
      description: 'Frontend helper — initializes and handles tokens',
    },
    {
      path: managerPath,
      content: managerTemplate,
      description: 'Zero-config Notification Manager component',
    },
    {
      path: configPath,
      content: renderTemplate(configTemplate, configVars),
      description: 'Firebase configuration file',
    },
    {
      path: usagePath,
      content: usageTemplate,
      description: 'Quick usage guide for your NotificationHandler',
    },
  ]

  const resolved = await checkConflicts(filesToWrite, project)

  // ── Write resolved files ──────────────────────────────────────────────
  for (const file of resolved) {
    const relativePath = path.relative(project.rootDir, file.path)

    if (file.action === 'skip') {
      scaffolded.push({
        absolutePath: file.path,
        relativePath,
        status: 'skipped',
        description: file.description,
      })
    } else {
      await writeFile(file.path, file.content)
      scaffolded.push({
        absolutePath: file.path,
        relativePath,
        status: file.path === swPath && swFilename === SERVICE_WORKER_FALLBACK_FILENAME ? 'created' : 'created',
        description: file.description,
      })
    }
  }

  // ── Post-scaffold info ────────────────────────────────────────────────
  if (swFilename !== SERVICE_WORKER_FILENAME) {
    logger.blank()
    logger.warn(`⚠  Service worker created as: public/${swFilename}`)
    logger.info(`   Update your config to use serviceWorkerPath: '/${swFilename}'`)
  }

  return scaffolded
}
