import { input, confirm } from '@inquirer/prompts'
import * as path from 'path'
import { logger } from '../utils/logger'
import { fileExists, writeFile, readFile, readJson } from '../utils/fileUtils'
import { renderTemplate } from '../core/templateEngine'
import { TEMPLATES_DIR, SW_TEMPLATE, SERVICE_WORKER_FILENAME, SERVICE_WORKER_FALLBACK_FILENAME } from '../constants'

interface ServiceWorkerConfig {
  apiKey: string
  authDomain: string
  projectId: string
  storageBucket: string
  messagingSenderId: string
  appId: string
}

interface OurPackageJson {
  firebase: ServiceWorkerConfig & { vapidKey: string }
}

export async function generateServiceWorker(): Promise<void> {
  const cwd = process.cwd()
  let firebaseConfig: ServiceWorkerConfig

  // ── 1. Try to load config from our_pkg.json ───────────────────────────
  const pkgConfigPath = path.join(cwd, 'our_pkg.json')
  if (await fileExists(pkgConfigPath)) {
    try {
      const packageConfig = await readJson<OurPackageJson>(pkgConfigPath)
      if (
        packageConfig.firebase &&
        packageConfig.firebase.apiKey &&
        packageConfig.firebase.projectId
      ) {
        logger.success('✓  Found Firebase configuration in our_pkg.json')
        logger.info(`   Project ID: ${packageConfig.firebase.projectId}`)
        logger.info(`   Auth Domain: ${packageConfig.firebase.authDomain}`)
        logger.blank()
        firebaseConfig = {
          apiKey: packageConfig.firebase.apiKey,
          authDomain: packageConfig.firebase.authDomain,
          projectId: packageConfig.firebase.projectId,
          storageBucket: packageConfig.firebase.storageBucket,
          messagingSenderId: packageConfig.firebase.messagingSenderId,
          appId: packageConfig.firebase.appId,
        }
      } else {
        logger.warn('⚠  our_pkg.json found but Firebase config is incomplete.')
        logger.info('   Falling back to manual input.')
        firebaseConfig = await getFirebaseConfigManually()
      }
    } catch (err: any) {
      logger.warn(`⚠  Could not parse our_pkg.json: ${err.message}`)
      logger.info('   Falling back to manual input.')
      firebaseConfig = await getFirebaseConfigManually()
    }
  } else {
    logger.info('ℹ  No our_pkg.json found. Manual Firebase configuration required.')
    logger.blank()
    firebaseConfig = await getFirebaseConfigManually()
  }

  // ── 2. Determine output path ──────────────────────────────────────────
  logger.blank()
  const publicDir = path.join(cwd, 'public')
  const defaultSwPath = path.join(publicDir, SERVICE_WORKER_FILENAME)

  // Check for naming collision
  let suggestedPath = `public/${SERVICE_WORKER_FILENAME}`
  if (await fileExists(defaultSwPath)) {
    const existingContent = await readFile(defaultSwPath).catch(() => '')
    if (!existingContent.includes('Generated by QuickFCM')) {
      suggestedPath = `public/${SERVICE_WORKER_FALLBACK_FILENAME}`
      logger.warn(`⚠  ${SERVICE_WORKER_FILENAME} already exists and was not generated by QuickFCM.`)
      logger.info(`   Defaulting output path to: ${suggestedPath}`)
    }
  }

  const outputPath = await input({
    message: `Output path (default: ${suggestedPath}):`,
    default: suggestedPath,
  })

  const absoluteOutputPath = path.resolve(cwd, outputPath.trim())

  // ── 3. Confirm overwrite if file exists ───────────────────────────────
  if (await fileExists(absoluteOutputPath)) {
    logger.warn(`⚠  File already exists: ${outputPath}`)
    const overwrite = await confirm({
      message: 'Overwrite existing file?',
      default: false,
    })

    if (!overwrite) {
      logger.info('ℹ  Cancelled. No files were changed.')
      return
    }
  }

  // ── 4. Read template and generate ────────────────────────────────────
  logger.blank()
  logger.info('ℹ  Generating service worker...')

  let template: string
  try {
    template = await readFile(path.join(TEMPLATES_DIR, SW_TEMPLATE))
  } catch (tplErr: any) {
    logger.error(`✖  Could not read service worker template: ${tplErr.message}`)
    logger.error(`   Expected template at: ${path.join(TEMPLATES_DIR, SW_TEMPLATE)}`)
    logger.error('   Try reinstalling QuickFCM: npm install -g quick-fcm')
    return
  }

  try {
    const content = renderTemplate(template, {
      API_KEY: firebaseConfig.apiKey,
      AUTH_DOMAIN: firebaseConfig.authDomain,
      PROJECT_ID: firebaseConfig.projectId,
      STORAGE_BUCKET: firebaseConfig.storageBucket,
      MESSAGING_SENDER_ID: firebaseConfig.messagingSenderId,
      APP_ID: firebaseConfig.appId,
    })

    await writeFile(absoluteOutputPath, content)
    logger.success(`✓  Service worker generated: ${outputPath}`)
    logger.blank()
    logger.info('  Next steps:')
    logger.info(`  1. Install package: npm install quick-fcm`)
    logger.info(`  2. Wrap your app: import { CustomPushProvider } from 'quick-fcm'`)
    logger.info(`  3. Request permission from a button click:`)
    logger.raw(`       const { requestPermission } = usePushMessage()`)
    logger.raw(`       <button onClick={() => requestPermission()}>Enable notifications</button>`)
  } catch (writeErr: any) {
    logger.error(`✖  Failed to write service worker: ${writeErr.message}`)
    logger.error(`   Target path: ${absoluteOutputPath}`)
    logger.error('   Ensure the output directory exists and you have write permissions.')
  }
}

async function getFirebaseConfigManually(): Promise<ServiceWorkerConfig> {
  logger.info('  Enter your Firebase web config:')
  logger.info('  Get it from: Firebase Console → Project Settings → Your apps → SDK setup')
  logger.blank()

  return {
    apiKey: await requiredInput('API Key:'),
    authDomain: await requiredInput('Auth Domain:'),
    projectId: await requiredInput('Project ID:'),
    storageBucket: await requiredInput('Storage Bucket:'),
    messagingSenderId: await requiredInput('Messaging Sender ID:'),
    appId: await requiredInput('App ID:'),
  }
}

async function requiredInput(message: string): Promise<string> {
  let value = ''
  while (!value.trim()) {
    value = await input({ message })
    if (!value.trim()) {
      logger.warn('  This field is required. Please enter a value.')
    }
  }
  return value.trim()
}
