// ─────────────────────────────────────────────────────────────────────────────
// Push Token Retrieval — Generated by pushfire (--files mode)
// Handles service worker registration and FCM token generation.
// Safari 16+ compatible with proper error messages.
// ─────────────────────────────────────────────────────────────────────────────

import { initializeApp, getApps, FirebaseApp } from 'firebase/app'
import { getMessaging, getToken } from 'firebase/messaging'
import { pushConfig } from './pushConfig'

export async function getPushToken(): Promise<string | null> {
  // Guard: must be in a browser
  if (typeof window === 'undefined') {
    console.warn('[push] getPushToken called in a non-browser environment. Skipping.')
    return null
  }

  if (!('serviceWorker' in navigator)) {
    console.warn('[push] Service Workers are not supported in this browser. Cannot get push token.')
    return null
  }

  if (!('Notification' in window)) {
    console.warn('[push] Notification API is not available. Cannot get push token.')
    return null
  }

  if (Notification.permission !== 'granted') {
    console.warn(
      '[push] Notification permission is not granted. ' +
      'Call requestPermission() first before getPushToken().'
    )
    return null
  }

  const swPath = pushConfig.serviceWorkerPath || '/{{SW_FILENAME}}'

  try {
    const app: FirebaseApp = getApps().length ? getApps()[0] : initializeApp(pushConfig)
    const messaging = getMessaging(app)

    // Register or reuse service worker
    // Use '/' scope so SW controls all pages — not just the SW file path
    let registration: ServiceWorkerRegistration

    try {
      // First try to find an existing registration for our SW file
      const registrations = await navigator.serviceWorker.getRegistrations()
      const existing = registrations.find(r => {
        const sw = r.active || r.waiting || r.installing
        return sw?.scriptURL.includes(swPath.replace(/^\//, ''))
      })

      if (existing) {
        registration = existing
      } else {
        registration = await navigator.serviceWorker.register(swPath, { scope: '/' })
        console.info(`[push] Service worker registered: ${swPath}`)
      }
    } catch (swErr: any) {
      console.error(
        '[push] Service worker registration failed:',
        swErr.message,
        `\n  → Ensure ${swPath} exists in your /public directory`,
        '\n  → Ensure it is served with the correct MIME type (application/javascript)',
        '\n  → For Next.js: use next-pwa or place the SW in the /public directory'
      )
      return null
    }

    // Wait for the service worker to be fully active
    await navigator.serviceWorker.ready

    const token = await getToken(messaging, {
      vapidKey: pushConfig.vapidKey,
      serviceWorkerRegistration: registration,
    })

    if (!token) {
      console.warn(
        '[push] Firebase returned an empty token. Possible causes:',
        '\n  → VAPID key may be incorrect or missing',
        '\n  → Service worker may not be in an active state',
        '\n  → Firebase project may not have Web Push enabled'
      )
      return null
    }

    return token
  } catch (error: any) {
    const ua = navigator.userAgent
    const isSafari = /^((?!chrome|android|crios|fxios|edgios|opr|firefox).)*safari/i.test(ua)

    if (isSafari) {
      console.error(
        '[push] Safari push token error:',
        error.message,
        '\n  → requestPermission() must be called directly from a user gesture (button click)',
        '\n  → VAPID key must be set in your Firebase project (Cloud Messaging settings)',
        '\n  → Safari 16+ is required for Web Push support',
        `\n  → Ensure the service worker file is accessible at: ${swPath}`
      )
    } else {
      console.error(
        '[push] Failed to get push token:',
        error.message,
        '\n  → Check your pushConfig.ts values (apiKey, appId, messagingSenderId)',
        '\n  → Check that VAPID key is correct'
      )
    }

    return null
  }
}
