'use client'

// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Provider — Generated by QuickFCM (--files mode)
// This is a standalone file — no QuickFCM runtime dependency required.
// ─────────────────────────────────────────────────────────────────────────────

import React, { createContext, useContext, useState, useCallback, useRef, useEffect } from 'react'
import { initializeApp, getApps } from 'firebase/app'
import { getMessaging, onMessage, Unsubscribe } from 'firebase/messaging'
import { getPushToken } from './getPushToken'
import { pushConfig } from './pushConfig'

// ── Types ───────────────────────────────────────────────────────────────────

export interface PushMessage {
  id: string
  title: string
  body: string
  icon?: string
  url?: string
  data?: Record<string, string>
  payload: any
  timestamp: number
}

export interface BrowserSupport {
  isSupported: boolean
  isSafari: boolean
  safariVersion: number | null
  requiresUserGesture: boolean
  reason?: string
}

export interface PushContextValue {
  token: string | null
  messages: PushMessage[]
  sendMessage: (title: string, body: string, data?: Record<string, string>) => Promise<void>
  clearMessages: () => void
  isSupported: boolean
  isPermissionGranted: boolean
  isTabActive: boolean
  browserSupport: BrowserSupport
  requestPermission: () => Promise<boolean>
}

// ── Safari / Browser Detection ──────────────────────────────────────────────

function detectBrowserSupport(): BrowserSupport {
  if (typeof window === 'undefined') {
    return {
      isSupported: false,
      isSafari: false,
      safariVersion: null,
      requiresUserGesture: false,
      reason: 'Server-side rendering (SSR) — push notifications require a browser',
    }
  }

  const ua = navigator.userAgent
  const isSafari = /^((?!chrome|android|crios|fxios|edgios|opr|firefox).)*safari/i.test(ua)

  let safariVersion: number | null = null
  if (isSafari) {
    const match = ua.match(/version\/(\d+)/i)
    safariVersion = match ? parseInt(match[1], 10) : null
  }

  if (!('serviceWorker' in navigator)) {
    return {
      isSupported: false,
      isSafari,
      safariVersion,
      requiresUserGesture: isSafari,
      reason: 'Service Workers are not supported in this browser',
    }
  }

  if (!('Notification' in window)) {
    return {
      isSupported: false,
      isSafari,
      safariVersion,
      requiresUserGesture: isSafari,
      reason: 'Notification API is not supported in this browser',
    }
  }

  if (!('PushManager' in window)) {
    if (isSafari && safariVersion !== null && safariVersion < 16) {
      return {
        isSupported: false,
        isSafari,
        safariVersion,
        requiresUserGesture: true,
        reason: `Safari ${safariVersion} does not support Web Push. Please update to Safari 16 or later.`,
      }
    }
    return {
      isSupported: false,
      isSafari,
      safariVersion,
      requiresUserGesture: isSafari,
      reason: 'Push API is not supported in this browser',
    }
  }

  return { isSupported: true, isSafari, safariVersion, requiresUserGesture: isSafari }
}

// ── Shared message builder ─────────────────────────────────────────────────

function buildMessage(payload: any): PushMessage {
  const messageUrl =
    payload.data?.action_url ||
    payload.data?.url ||
    payload.data?.route ||
    payload.data?.click_action ||
    payload.fcmOptions?.link ||
    undefined

  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    title: payload.notification?.title || payload.data?.title || 'New notification',
    body: payload.notification?.body || payload.data?.body || '',
    icon: payload.notification?.icon || payload.data?.icon,
    url: messageUrl,
    data: payload.data as Record<string, string> | undefined,
    payload,
    timestamp: Date.now(),
  }
}

// ── Context ─────────────────────────────────────────────────────────────────

export const PushContext = createContext<PushContextValue | null>(null)

interface CustomPushProviderProps {
  children: React.ReactNode
  /**
   * Called when a foreground message arrives and the tab IS active.
   * Use this to show an in-app toast instead of a native notification.
   */
  onToast?: (message: PushMessage) => void
}

export function CustomPushProvider({ children, onToast }: CustomPushProviderProps) {
  const [token, setToken] = useState<string | null>(null)
  const [messages, setMessages] = useState<PushMessage[]>([])
  const [isPermissionGranted, setIsPermissionGranted] = useState(
    typeof window !== 'undefined' ? Notification.permission === 'granted' : false
  )
  const [isTabActive, setIsTabActive] = useState(true)

  const initialized = useRef(false)
  const messagingUnsubRef = useRef<Unsubscribe | null>(null)
  const [browserSupport] = useState<BrowserSupport>(() => detectBrowserSupport())
  const isSupported = browserSupport.isSupported

  // Tab visibility
  useEffect(() => {
    if (typeof document === 'undefined') return
    const handler = () => setIsTabActive(document.visibilityState === 'visible')
    setIsTabActive(document.visibilityState === 'visible')
    document.addEventListener('visibilitychange', handler)
    return () => document.removeEventListener('visibilitychange', handler)
  }, [])

  const setupMessaging = useCallback(async () => {
    try {
      const app = getApps().length ? getApps()[0] : initializeApp(pushConfig)
      const messaging = getMessaging(app)

      const fcmToken = await getPushToken()
      if (fcmToken) {
        setToken(fcmToken)
        // Optionally register token with your backend here:
        // if (pushConfig.registerUrl) {
        //   try {
        //     await fetch(pushConfig.registerUrl, {
        //       method: 'POST',
        //       headers: { 'Content-Type': 'application/json' },
        //       body: JSON.stringify({ token: fcmToken }),
        //     })
        //   } catch (backendErr: any) {
        //     console.error('[push] Failed to register token with backend:', backendErr.message)
        //   }
        // }
      } else {
        console.warn(
          '[push] Could not retrieve FCM token. ' +
          'Push notifications may not work. Check VAPID key and service worker path.'
        )
      }

      // Tear down previous listener
      if (messagingUnsubRef.current) {
        messagingUnsubRef.current()
      }

      messagingUnsubRef.current = onMessage(messaging, (payload) => {
        const newMessage = buildMessage(payload)

        if (document.visibilityState === 'visible' && onToast) {
          try {
            onToast(newMessage)
          } catch (toastErr: any) {
            console.error('[push] onToast callback threw an error:', toastErr.message)
          }
        }

        setMessages(prev => [...prev, newMessage])
      })
    } catch (err: any) {
      console.error(
        '[push] Firebase messaging initialization failed:',
        err.message,
        '\n  → Check your pushConfig.ts (apiKey, appId, etc.)',
        '\n  → Check that the service worker file exists in /public/'
      )
    }
  }, [onToast])

  // Safari: must call requestPermission from a user gesture (button click)
  const requestPermission = useCallback(async (): Promise<boolean> => {
    if (!isSupported) {
      console.warn('[push] Push notifications not supported:', browserSupport.reason)
      return false
    }

    if (token) {
      console.info('[push] Push already initialized. Token:', token.slice(0, 12) + '...')
      return true
    }

    let result: NotificationPermission
    try {
      result = await Notification.requestPermission()
    } catch (permErr: any) {
      console.error(
        '[push] Permission request failed:',
        permErr.message,
        '\n  → Ensure requestPermission() is called directly inside a click handler',
        '\n  → Safari does not allow requesting permission programmatically'
      )
      return false
    }

    if (result === 'denied') {
      console.warn('[push] Notification permission denied by user. Re-enable in settings.')
      setIsPermissionGranted(false)
      return false
    }

    if (result === 'default') {
      console.info('[push] Notification permission dismissed.')
      return false
    }

    setIsPermissionGranted(true)
    await setupMessaging()
    return true
  }, [isSupported, token, browserSupport.reason, setupMessaging])

  // Auto-init if already granted
  useEffect(() => {
    if (initialized.current || !isSupported) return
    initialized.current = true

    if (Notification.permission === 'granted') {
      setIsPermissionGranted(true)
      setupMessaging()
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Cleanup
  useEffect(() => {
    return () => {
      if (messagingUnsubRef.current) {
        messagingUnsubRef.current()
        messagingUnsubRef.current = null
      }
    }
  }, [])

  const sendMessage = useCallback(async (title: string, body: string, data?: Record<string, string>) => {
    if (!token) throw new Error('[push] No push token. Call requestPermission() first.')
    // Send via your backend — adjust the URL to match your API
    const sendUrl = pushConfig.registerUrl ? pushConfig.registerUrl.replace(/\/register\/?$/, '/send') : '/api/push/send'
    
    try {
      const res = await fetch(sendUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, title, body, data }),
      })
      if (!res.ok) {
        throw new Error(`Backend returned HTTP ${res.status}`)
      }
    } catch (sendErr: any) {
      console.error('[push] sendMessage failed:', sendErr.message)
      throw sendErr
    }
  }, [token])

  const clearMessages = useCallback(() => setMessages([]), [])

  return (
    <PushContext.Provider value={{
      token, messages, sendMessage, clearMessages,
      isSupported, isPermissionGranted, isTabActive,
      browserSupport, requestPermission,
    }}>
      {children}
    </PushContext.Provider>
  )
}
