# Push Notification Integration Guide

> Generated by [QuickFCM](https://github.com/dushyantkhoda-web/QuickFCM) — standalone files mode

---

## Quick Start

### 1. Wrap your app with `CustomPushProvider`

```tsx
// App.tsx or main.tsx
import { CustomPushProvider } from './push-notification/pushProvider'

function App() {
  return (
    <CustomPushProvider
      onToast={(msg) => {
        // Show in-app toast when tab is active
        // Plug in your toast library here (react-hot-toast, sonner, etc.)
        console.log('Toast:', msg.title, msg.body)
      }}
    >
      <YourApp />
    </CustomPushProvider>
  )
}
```

### 2. Request permission from a button click

```tsx
import { usePushMessage } from './push-notification/usePushMessage'

function EnableNotifications() {
  const { requestPermission, isPermissionGranted, browserSupport } = usePushMessage()

  if (!browserSupport.isSupported) {
    return <p>{browserSupport.reason}</p>
  }

  return (
    <button onClick={() => requestPermission()}>
      {isPermissionGranted ? '✓ Notifications enabled' : 'Enable notifications'}
    </button>
  )
}
```

> **⚠ Safari requires** `requestPermission()` to be called from a **user gesture**
> (button click). It will silently fail if called automatically.

### 3. Access messages and token

```tsx
import { usePushMessage } from './push-notification/usePushMessage'

function NotificationBell() {
  const { messages, token, clearMessages } = usePushMessage()

  return (
    <div>
      <span>{messages.length} new</span>
      <div>
        {messages.map(msg => (
          <div key={msg.id}>
            <strong>{msg.title}</strong>
            <p>{msg.body}</p>
          </div>
        ))}
      </div>
      <button onClick={clearMessages}>Clear</button>
    </div>
  )
}
```

---

## Configuration

Edit `pushConfig.ts` to update your Firebase credentials.

**Environment Variables** — store secrets in `.env`:

```env
{{ENV_PREFIX}}_FIREBASE_API_KEY=your-api-key
{{ENV_PREFIX}}_FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com
{{ENV_PREFIX}}_FIREBASE_PROJECT_ID=your-project-id
{{ENV_PREFIX}}_FIREBASE_STORAGE_BUCKET=your-project.appspot.com
{{ENV_PREFIX}}_FIREBASE_MESSAGING_SENDER_ID=123456789
{{ENV_PREFIX}}_FIREBASE_APP_ID=1:123456789:web:abc123
{{ENV_PREFIX}}_FIREBASE_VAPID_KEY=your-vapid-key
```

> Get VAPID key from: [Firebase Console → Cloud Messaging](https://console.firebase.google.com/project/_/settings/cloudmessaging)

---

## Service Worker

The service worker file (`{{SW_FILENAME}}`) must be in your `public/` directory.
It handles background push notifications and notification click redirects.

- **Vite**: `public/{{SW_FILENAME}}`
- **Next.js**: `public/{{SW_FILENAME}}`

---

## Safari Notes

| Feature | Chrome/Firefox | Safari 16+ | Safari < 16 |
|---------|---------------|------------|-------------|
| Web Push | ✓ | ✓ (VAPID only) | ✗ Not supported |
| Auto-permission | ✓ | ✗ Requires user gesture | ✗ |
| FCM Direct | ✓ | ✗ Use VAPID | ✗ |
| Notification click | `client.navigate()` | `clients.openWindow()` fallback | N/A |

---

## How it Works

- **Tab is active** → `onToast` callback fires → show in-app toast
- **Tab is inactive / different tab** → native push notification appears
- **Notification clicked** → service worker redirects to the URL in the payload

---

## Files Reference

| File | Purpose |
|------|---------|
| `pushProvider.tsx` | React context provider with Safari detection |
| `usePushMessage.ts` | Hook to access push state and methods |
| `pushConfig.ts` | Firebase configuration (edit this) |
| `getPushToken.ts` | Token retrieval with SW registration |
| `USAGE.md` | This file |

---

## Need help?

- [Firebase Cloud Messaging Docs](https://firebase.google.com/docs/cloud-messaging)
- [Web Push on Safari](https://developer.apple.com/documentation/usernotifications/sending-web-push-notifications-in-web-apps-and-browsers)
- [QuickFCM GitHub](https://github.com/dushyantkhoda-web/QuickFCM)
