// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Hook — Generated by pushfire (--files mode)
// ─────────────────────────────────────────────────────────────────────────────

import { useContext } from 'react'
import { PushContext, PushContextValue } from './pushProvider'

/**
 * Hook to access push notification state and methods.
 * Must be used inside <CustomPushProvider>.
 *
 * Usage:
 *   const { token, messages, requestPermission, browserSupport } = usePushMessage()
 *
 * Safari Note:
 *   requestPermission() MUST be called from a user gesture (button click).
 *   Safari will silently fail if called outside a click handler.
 */
export function usePushMessage(): PushContextValue {
  const ctx = useContext(PushContext)
  if (!ctx) {
    throw new Error(
      'usePushMessage must be used inside <CustomPushProvider>. ' +
      'Wrap your app with <CustomPushProvider> in your root component.'
    )
  }
  return ctx
}
