// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Config — Generated by QuickFCM
// Values are read directly from quickfcm.config.json (no env vars needed).
// ─────────────────────────────────────────────────────────────────────────────

// @ts-ignore
import pkg from '../../quickfcm.config.json'

export const pushConfig = {
  apiKey:            pkg.firebase.apiKey,
  authDomain:        pkg.firebase.authDomain,
  projectId:         pkg.firebase.projectId,
  storageBucket:     pkg.firebase.storageBucket,
  messagingSenderId: pkg.firebase.messagingSenderId,
  appId:             pkg.firebase.appId,
  vapidKey:          pkg.firebase.vapidKey,
  serviceWorkerPath: '/{{SW_FILENAME}}',
  registerUrl:       pkg.backend?.registerUrl ?? '/api/push/register',
}
