// Generated by QuickFCM — edit as needed.
import { usePush } from 'quick-fcm'
import QuickFCMConfig from '../../quickfcm.config.json'

export function usePushNotification() {
  return usePush({
    config: {
      ...QuickFCMConfig.firebase,
      serviceWorkerPath: QuickFCMConfig.serviceWorker.path,
      registerUrl: QuickFCMConfig.backend.registerUrl || undefined,
    },
    onMessage: (message) => {
      console.log('[push] Received background/native message:', message.title)
    },
    onToast: (message) => {
      // Foreground push received while tab is active — plug in your toast library here
      console.log('[push] Active tab message:', message.title, message.body)
      alert(`New Notification: ${message.title}\n${message.body}`)
    },
    onTokenChange: (token) => {
      console.log('[push] Token updated:', token)
    }
  })
}
