'use client';

import { useEffect } from 'react';
import { usePushMessage } from 'pushfire';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * PushNotificationManager — Generated by pushfire
 * ─────────────────────────────────────────────────────────────────────────────
 * This component handles:
 *  1. Logging the FCM token on mount (if available)
 *  2. Displaying toasts for incoming foreground messages
 *  3. Monitoring permission status
 * 
 * To use a custom toast library (e.g. Sonner, React Hot Toast):
 * Replace the alert()/console.log() calls in the useEffect below.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export function PushNotificationManager() {
  const { token, messages, isPermissionGranted } = usePushMessage();

  // Log token for debugging (can be removed in production)
  useEffect(() => {
    if (token) {
      console.log('[push] FCM Token:', token);
    }
  }, [token]);

  // Handle incoming foreground messages
  useEffect(() => {
    if (messages.length > 0) {
      const lastMessage = messages[messages.length - 1];
      console.log('[push] Foreground message received:', lastMessage);
      
      // 🚀 CUSTOM TOAST LOGIC HERE
      // Example with Sonner:
      // toast(lastMessage.title || 'New Notification', { description: lastMessage.body });
      
      // Fallback/Default:
      if (typeof window !== 'undefined') {
        // You should replace this with a professional toast library
        alert(`[Push] ${lastMessage.title}\n${lastMessage.body}`);
      }
    }
  }, [messages]);

  // Monitor permission status
  useEffect(() => {
    if (!isPermissionGranted && typeof Notification !== 'undefined') {
      if (Notification.permission === 'default') {
        console.log('[push] Permission not yet requested.');
      } else if (Notification.permission === 'denied') {
        console.warn('[push] Permission denied by user.');
      }
    }
  }, [isPermissionGranted]);

  return null; // This component is a global logic handler (invisible)
}
