'use client';

// ─────────────────────────────────────────────────────────────────────────────
// PushProvider — Generated by QuickFCM
// Wraps your Next.js layout with the push notification context.
// Usage: Import and wrap your root layout children with <PushProvider>.
// ─────────────────────────────────────────────────────────────────────────────

import { CustomPushProvider } from 'quick-fcm';
import { pushConfig } from '@/NotificationHandler/config';
import { PushNotificationManager } from '@/NotificationHandler/PushNotificationManager';

export function PushProvider({ children }: { children: React.ReactNode }) {
  return (
    <CustomPushProvider config={pushConfig}>
      <PushNotificationManager />
      {children}
    </CustomPushProvider>
  );
}
