// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Config — Generated by QuickFCM
// ─────────────────────────────────────────────────────────────────────────────

export const pushConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY!,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN!,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID!,
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET!,
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID!,
  appId: process.env.REACT_APP_FIREBASE_APP_ID!,
  vapidKey: process.env.REACT_APP_FIREBASE_VAPID_KEY!,
  registerUrl: '/api/push/register', // Replace with your backend registration endpoint
}
