// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Config — Generated by QuickFCM
// ─────────────────────────────────────────────────────────────────────────────

export const pushConfig = {
  apiKey: process.env.{{ENV_PREFIX}}FCM_API_KEY || '',
  authDomain: process.env.{{ENV_PREFIX}}FCM_AUTH_DOMAIN || '',
  projectId: process.env.{{ENV_PREFIX}}FCM_PROJECT_ID || '',
  storageBucket: process.env.{{ENV_PREFIX}}FCM_STORAGE_BUCKET || '',
  messagingSenderId: process.env.{{ENV_PREFIX}}FCM_MESSAGING_SENDER_ID || '',
  appId: process.env.{{ENV_PREFIX}}FCM_APP_ID || '',
  vapidKey: process.env.{{ENV_PREFIX}}FCM_VAPID_KEY || '',
  registerUrl: '/api/push/register', // Replace with your backend registration endpoint
}
